### ISSUE TITLE
Can't open WebP

### ISSUE THREAD

**Issue by waterman13** [Doraemoe/DuReader#105]
Hi, I can't open archive using webp image, is that a bug or is webp not supported yet?

**Comment by Doraemoe** [comment]
iOS should support webp image by default. Could you please upload a sample archive with webp images? Thanks.

**Comment by waterman13** [comment]
[Sample Archive](https://raw.githubusercontent.com/waterman13/etc/main/SampleArchive.zip). Thank you.

**Comment by Doraemoe** [comment]
Strange, that sample works for me. What device and iOS version you are using? Also, have you tried to turn it off and on again 😂

**Comment by waterman13** [comment]
iPhone 7 Plus, iOS 14.8. I've already tried that. I also tried to check web traffic using Fiddler, everything looks normal.
[Error message](https://raw.githubusercontent.com/waterman13/etc/main/error.jpg).
[PNG archives have no problems](https://raw.githubusercontent.com/waterman13/etc/main/normal.jpg).

**Comment by waterman13** [comment]
iPhone 7 Plus, iOS 14.8. I've already tried that. I also tried to check web traffic using Fiddler, everything looks normal.
[Error message](https://raw.githubusercontent.com/waterman13/etc/main/error.jpg).
[PNG archives have no problems](https://raw.githubusercontent.com/waterman13/etc/main/normal.jpg).

**Comment by Doraemoe** [comment]
I just pushed a new version and hopefully it can help us pin down the issue. 
- Please install 1.0 (19) from TestFlight
- Make sure you **DISABLE** the experimental read in the settings
- Try reproduce the problem you have
- Go to settings -> Application log (at the bottom in debug section)
If there are any log, please long press and copy paste those logs here (redact any sensitive information if there are any). If there aren't anything... I will see what I can do next.

**Comment by waterman13** [comment]
It's [working](https://raw.githubusercontent.com/waterman13/etc/main/working.jpg) now, log is [empty](https://raw.githubusercontent.com/waterman13/etc/main/logempty.jpg). Thank you very much.

**Comment by Doraemoe** [comment]
Great
