### ISSUE TITLE
What to enter in api and source

### ISSUE THREAD

**Issue by Cordisl** [Doraemoe/DuReader#107]
![image](https://user-images.githubusercontent.com/91519164/135028628-90e0bb75-8073-4227-b8f7-2a8c755b2836.jpeg)

**Comment by Doraemoe** [comment]
They all depend on how you configured your LANraragi server. The first one is the location of you LANraragi server. i.e. what you enter in your web browser to access LANraragi? The second one is api key you set in LANraragi -> Settings -> Security -> API Key. This value, by default, is empty.

**Comment by Cordisl** [comment]
What is LANraragi 😅😅

**Comment by Doraemoe** [comment]
This is a client for LANraragi, if you don’t know what is that, you didn’t need this app.

**Comment by Cordisl** [comment]
Is this app for reading manga

**Comment by BruhLmao420** [comment]
Thanks for the quick reply, I'll see what I can find on those channels

**Comment by BruhLmao420** [comment]
Hello dev, I have acquired the local host and can access on web and through LRReader but still cannot connect through LANreader through appstore download or Altstore saying the request timed out. I apologize in advance for the second ping.

**Comment by Doraemoe** [comment]
> Hello dev, I have acquired the local host and can access on web and through LRReader but still cannot connect through LANreader through appstore download or Altstore saying the request timed out. I apologize in advance for the second ping.

I will need some more details, like do you see any error message? Are you using API secret? Are you using reverse proxy or ip address directly?

Also you should create a new issue instead using this unrelated one.
