### ISSUE TITLE
can't load media library

### ISSUE THREAD

**Issue by simplify123** [Doraemoe/DuReader#113]
hi,
   i use altstore installed dumanga.ipa on my iphone11(version:15.7),after set server ip,dumanga can recognize category correctly,but can't load media libyary,says that check server setting,i don't know how to to...maybe a bug?

**Comment by Doraemoe** [comment]
Which Lanraragi version you are using? Can you take a screenshot of the error please?
Also, when you say category works, do you mean you can read manga via catalog or only catalog list works?

**Comment by windroad77** [comment]
I have same problem. 
- Iphone 14 pro max, ios 16.1
- Lanraragi version:  v.0.8.7, docker
- Error Message: Cannot load library, please try again or check your server settings.

**Comment by Doraemoe** [comment]
Just want to make sure, only library view will throw this error, catalog or search view works fine?

**Comment by windroad77** [comment]
> Just want to make sure, only library view will throw this error, catalog or search view works fine?
Neither the catalog nor the search view works.

**Comment by Doraemoe** [comment]
Ok, can you try use this attached version. After you see the error message, go to settings -> debug -> log and copy paste error message here. Thanks.

[DM.ipa.zip](https://github.com/Doraemoe/DuReader/files/9948340/DM.ipa.zip)

**Comment by windroad77** [comment]
Log
--------------------------------------------------------------------------------------------------------------------------------------------
2022-11-07T14:25:50+0900 error LANraragiService : failed to fetch archive index: sessionTaskFailed(error: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x2834a8480 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <66A05568-5127-4880-A654-87A1327B4EE7>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <66A05568-5127-4880-A654-87A1327B4EE7>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=http://MyIP:MyPort/api/archives, NSErrorFailingURLKey=http://MyIP:MyPort/api/archives, _kCFStreamErrorDomainKey=4})

**Comment by Doraemoe** [comment]
Hmmm, It says request timed out, that means it can't connect to the server. Do you have anything like firewall that prevent connection? Can you connect outside of this app?

**Comment by windroad77** [comment]
> Hmmm, It says request timed out, that means it can't connect to the server. Do you have anything like firewall that prevent connection? Can you connect outside of this app?

After setting it to port forwarding, I can connect from the outside using the IP and port on the web. 
When connecting to the web, after entering the password set in Lanraragi, the library is displayed.

**Comment by Doraemoe** [comment]
If you are accessing the library via internet, you have to setup https on your server. iOS does not allow http connection in app since iOS 11.

**Comment by windroad77** [comment]
I set up https on Synology and installed Lanraragi with docker.
Fixed the issue when checking.
Thank you.

**Comment by Doraemoe** [comment]
Great

@simplify123 is your problem the same?
