### ISSUE TITLE
Swipe Options Not Working 

### ISSUE THREAD

**Issue by mslmn** [Doraemoe/DuReader#145]
The reader is Right to Left by default but changing the swipe right/left option in settings isn’t reflected in the reader. I even tried toggle navigation and that doesn’t work either. 

The tap on right/left side settings work fine. I’m running the latest release.

**Comment by Doraemoe** [comment]
Oops, the swipe direction option was for the old reader implementation I forgot to remove, it doesn't work on current page view. I may implement it again in the future but for now I will just remove the options.

**Comment by Doraemoe** [comment]
Turns out it's not hard to implement, please try the new version.
