### ISSUE TITLE
Delete source from server

### ISSUE THREAD

**Issue by CuddleBear92** [Doraemoe/DuReader#81]
An option to delete comics from the server could be useful since the server does not have any duplicate processing among other things.
To be able to browse in the app and spot something weird and delete problem comics could be wanted.

Delete button should not be easy to mis-tap, maybe hidden in a `...` tripple doted menu or something for more advance options.

**Comment by Doraemoe** [comment]
LANraragi doesn't have a delete api yet, so this is not possible for now.

**Comment by Doraemoe** [comment]
Reopen as 0.7.8 now support delete endpoint
